package com.neutral.xianxia.ui;

import com.neutral.xianxia.logic.System;

/*
 * Copyright (C) 2019 Mr.Neutral
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 *
 * @author Mr.Neutral
 */
public class GameInterface extends javax.swing.JFrame {

    /**
     * Creates new form GameInterface
     */
    private System system;

    public GameInterface(System system) {
        this.system = system;
        initComponents();
        updateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        playerInfoPanel = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        levelData = new javax.swing.JLabel();
        bodyLabel = new javax.swing.JLabel();
        bodyData = new javax.swing.JLabel();
        qiLabel = new javax.swing.JLabel();
        qiData = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        expData = new javax.swing.JLabel();
        cultivateButton = new javax.swing.JButton();
        levelUpButton = new javax.swing.JButton();
        exploreButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XianxiaAdventures");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        actionPanel.setLayout(new java.awt.GridBagLayout());

        playerInfoPanel.setLayout(new java.awt.GridLayout(4, 2));

        levelLabel.setText("Level:");
        playerInfoPanel.add(levelLabel);

        levelData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerInfoPanel.add(levelData);

        bodyLabel.setText("Body:");
        playerInfoPanel.add(bodyLabel);

        bodyData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerInfoPanel.add(bodyData);

        qiLabel.setText("Qi:");
        playerInfoPanel.add(qiLabel);

        qiData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerInfoPanel.add(qiData);

        expLabel.setText("Exp:");
        playerInfoPanel.add(expLabel);

        expData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerInfoPanel.add(expData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        actionPanel.add(playerInfoPanel, gridBagConstraints);

        cultivateButton.setText("Cultivate");
        cultivateButton.setFocusable(false);
        cultivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cultivateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        actionPanel.add(cultivateButton, gridBagConstraints);

        levelUpButton.setText("Level Up");
        levelUpButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        actionPanel.add(levelUpButton, gridBagConstraints);

        exploreButton.setText("Explore");
        exploreButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        actionPanel.add(exploreButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(actionPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cultivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cultivateButtonActionPerformed
        // TODO add your handling code here:
        system.cultivate();
        expData.setText(String.valueOf(system.getPlayerExp()));
    }//GEN-LAST:event_cultivateButtonActionPerformed

    private void updateData() {
        levelData.setText(String.valueOf(system.getPlayerLevel()));
        bodyData.setText(String.valueOf(system.getPlayerBody()));
        qiData.setText(String.valueOf(system.getPlayerQi()));
        expData.setText(String.valueOf(system.getPlayerExp()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JLabel bodyData;
    private javax.swing.JLabel bodyLabel;
    private javax.swing.JButton cultivateButton;
    private javax.swing.JLabel expData;
    private javax.swing.JLabel expLabel;
    private javax.swing.JButton exploreButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel levelData;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton levelUpButton;
    private javax.swing.JPanel playerInfoPanel;
    private javax.swing.JLabel qiData;
    private javax.swing.JLabel qiLabel;
    // End of variables declaration//GEN-END:variables
}
