package com.neutral.xianxia.ui;

/*
 * Copyright (C) 2019 Mr.Neutral
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 *
 * @author Mr.Neutral
 */
public class GameInterface extends javax.swing.JFrame {

    /**
     * Creates new form GameInterface
     */
    public GameInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        actionPanel = new javax.swing.JPanel();
        playerInfoPanel = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        levelData = new javax.swing.JLabel();
        bodyLabel = new javax.swing.JLabel();
        bodyData = new javax.swing.JLabel();
        qiLabel = new javax.swing.JLabel();
        qiData = new javax.swing.JLabel();
        cultivateButton = new javax.swing.JButton();
        levelUpButton = new javax.swing.JButton();
        exploreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XianxiaAdventures");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        actionPanel.setLayout(new java.awt.GridBagLayout());

        playerInfoPanel.setLayout(new java.awt.GridLayout(3, 2));

        levelLabel.setText("Level:");
        playerInfoPanel.add(levelLabel);

        levelData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        levelData.setText("1");
        playerInfoPanel.add(levelData);

        bodyLabel.setText("Body:");
        playerInfoPanel.add(bodyLabel);

        bodyData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bodyData.setText("2");
        playerInfoPanel.add(bodyData);

        qiLabel.setText("Qi:");
        playerInfoPanel.add(qiLabel);

        qiData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        qiData.setText("3");
        playerInfoPanel.add(qiData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        actionPanel.add(playerInfoPanel, gridBagConstraints);

        cultivateButton.setText("Cultivate");
        cultivateButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        actionPanel.add(cultivateButton, gridBagConstraints);

        levelUpButton.setText("Level Up");
        levelUpButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        actionPanel.add(levelUpButton, gridBagConstraints);

        exploreButton.setText("Explore");
        exploreButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        actionPanel.add(exploreButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(actionPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JLabel bodyData;
    private javax.swing.JLabel bodyLabel;
    private javax.swing.JButton cultivateButton;
    private javax.swing.JButton exploreButton;
    private javax.swing.JLabel levelData;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton levelUpButton;
    private javax.swing.JPanel playerInfoPanel;
    private javax.swing.JLabel qiData;
    private javax.swing.JLabel qiLabel;
    // End of variables declaration//GEN-END:variables
}
